services:
  royalroadbot:
    build: .
    networks:
      - royalroadbot-network
    ports:
      - "8090:8090"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27017
networks:
  royalroadbot-network:
