services:
  mongo-express:
    image: mongo-express:latest
    networks:
      - royalroadbot-network
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo:27017

networks:
  royalroadbot-network:
