services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - royalroadbot-network
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27017
    command: >
      sh -c "
        while ! nc -z mongo 27017; do
          echo 'Waiting for MongoDB to be ready...'
          sleep 1
        done
        go test ./app/... -v
      "

networks:
  royalroadbot-network:
